version: '3.5'


services:

  redis:
    image: redis:latest
    container_name: redis_fastapi_db
    ports:
      - 6379:6379
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    volumes:
      - redis-data:/data


  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=redis
    ports: 
      - 8081:8081
    depends_on: 
      - redis

volumes:
  redis-data:
